### PR TITLE
add: feature to run optional arbitrary additional commands with cronjob

### PR DESCRIPTION
**Pull request by whysthatso**
i'm running all my production cronjobs with an additional command that 'pings' a healthchecks server, hence i needed a way to add this command after the backup run, and this is my proposed solution. might be useful as a general feature.

i've added this feature in a rather naive way for now, very open to feedback to make this more round and fluffy.

### CODE REVIEW

**Comment by whysthatso** [comment]
i'm not sure how my commit from november made it into this pr, does that matter, or how could i remove it?

**Comment by mleutenegger** [comment]
Thanks for the PR! I can see the usecase for this feature, and I'm all for including it. This kind of concerns the same problem as #21.

However, I'm a bit worried about appending the command directly to the cronjob, as this would create an escape hatch to add all kinds of things to the actual backup command defined in the generated script. We do after all append all input after the call directly to the generated command:
https://github.com/arillso/ansible.restic/blob/1156712b1695636d504c6eb057f21f8dfc6d4146/templates/restic_script_Linux.j2#L120
This could lead to custom "fixes" for all kind of problems which later on might break the backups on upgrading this role. I can see two ways of navigating around this problem:
1. append all custom commands after a `&&` which is hardcoded
2. append/prepend custom commands directly in the generated backup script.

Personally, I would prefer 2), as it would allow to add a list of commands. This also feels cleaner and gives more dynamic control over the commands. Another benefit would be the addition `pre_` and `post_` commands, enabling more complex backup workflows. For example, this could look like the this
```yaml
pre_backup_commands:
  - export-task
post_backup_commands:
  - curl healthchecks.yourdomain.com > /dev/null
```
The only downside for your specific usecase would be that the commands will also be executed when a backup script is manually executed, but this should not really make a difference for a healthcheck. Do you think you can adapt your PR that way?

**Comment by whysthatso** [comment]
Hey,
thanks for your constructive review, you are making some excellent points there. i will try to get to this as soon as i can.

**Comment by bachya** [comment]
@whysthatso I'm very interested in seeing this pushed forward – would help be helpful? 😄

**Comment by whysthatso** [comment]
@mleutenegger i've reworked this according to your second proposal, hope i got you right. sorry for the slightly messy commit history, and i'm not sure what the merge conflicts are really.

**Comment by liambresnahan** [comment]
this is a nice PR, is there anything that I can do to help? Looks like it just needs merging, right? 

One thing for the future (I would imagine it needs to be a new PR) would be interesting on how errors are dealt with. i.e. if the pre/post command fails, what happens next? I really like this PR as it allows something I'd like to do (mount/umount a location prior to running the backup) but if that failed obviously so will the backup. It'd be good to make sure that failure is captured and added to the log as an ERROR. Is that how this would work today? Looking at the code I imagine it's just a case of adding something similar to this below the pre/post commit block:

`if [[ $? -eq 0 ]]
then
    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
 else
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
 fi`

**Comment by mleutenegger** [comment]
Sorry for the late reply, this somehow went under my radar.

First off, the PR is looking good so far @whysthatso. I'll give it a spin later today.

-------

@liambresnahan Error handling is a very good point. The current way of handling errors is to just dump them in a log if they fail and rely on the host to have some contingency measure (like sending an email) in case a cronjob fails. Currently, this should be enough as we only execute two commands which can fail, producing a result and output log each.

As we use the `[[ $? -eq 0 ]]` check, we only test if the backup or forget command failed. Any failed pre-command would not be logged/considered a failure in the result log. This is definitely not ideal, as it could lead to situations where the backup "fails" but is actually registered as `OK`. An example would be a backup process where one would dump multiple DBs in a directory via pre-tasks and then backup said directory. If the pre-tasks fail, the directory would be empty but the backup will succeed without backuping any data.

From my point of view, merging this PR as-is would expose users of this role to the danger of losing data, so the error handling issue is therefore something this PR should adress before merging. The generated script should at least fulfill the following:
* After each pre-task, the exit status is checked and if the command did not succeed:
  * An `ERROR - pre_backup_command ({{ command }}) failed` message is appended to `backup_result_log` and `forget_result_log` (enables monitoring to pick up errors)
  * the script exits with the exit code of the pre-command (no backup executed)
* After each post-task, the exit status is checked and if the command did not succeed:
  * An `ERROR - post_backup_command ({{ command }}) failed` is appended to a `post_backup_result_log` (enables monitoring of post backup cleanup in case of security related stuff)

@liambresnahan, @whysthatso does my logic make sense? (😅)
@whysthatso do you think you could add these features?

**Comment by liambresnahan** [comment]
Logic makes sense to me @mleutenegger I am also happy to try to help if I can @whysthatso

**Comment by whysthatso** [comment]
> Logic makes sense to me @mleutenegger 

yep.

> I am also happy to try to help if I can @whysthatso

sure, go for it.

**Comment by whysthatso** [comment]
so, after a bit of a break i had another go at the hooks system and the logging. maybe @liambresnahan and @mleutenegger could have a look and comment if i'm on the right track.

i'm not too fluent in bash scripting so if there are possible improvements, i'd gladly improve on the implementation details.

right now i've focused on giving the most obvious places hookable instances: around the backup command and around the prune command. all of course optional.

I've also opted for an extra log file, as this does not break anybody already parsing the OK / ERROR from the other logs. hooks should be identified by a snippet of the first 30 characters of the command, that being an arbitrary helper in case somebody has many commands.

**Comment by whysthatso** [comment]
i've moved on to use autorestic and its elaborate hook system, along with https://github.com/dbrennand/ansible-role-autorestic to manage it, so i would like to abandon this pr, hand it over, or close it. is that okay with everybody?

**Pull request closed without merging**
