### PR TITLE
master: use dicts everywhere to make the config more readable and add…

### PR DESCRIPTION
**Pull request by gilesw**
… auto_restore feature

### CODE REVIEW

**Comment by gilesw** [comment]
oh i've also made the cronjob into a cronfile as they are much nicer to manage

**Comment by mleutenegger** [comment]
Hi @gilesw,

First off, thanks for your pull request. I will have a look at your proposed changes and give feedback. A few points to have a look at already:

- please make sure, that the pipeline passes, there are some linting errors
- please add your changes to the changelog under the Unreleased section

Thanks!

**Comment by mleutenegger** [comment]
After reviewing the changes, I say that the change to add a restore script and to use cron files instead is a very nice change. However, I do have two issues in terms of backwards compatibility:

* Already established setups use the normal cronjobs, so these need to be removed
* Changing the backup array to a dict requires all users to change all backup definitions.

In order to make further work easier, I would suggest you split up the features into different pull requests following the [contribution guide](https://github.com/arillso/ansible.restic/blob/master/CONTRIBUTING.md) (which I finally came around of adding).

**Comment by silfreed** [comment]
This is exactly what I was hoping for when managing my Raspberry Pi installs - backup existing configs unless the SD card dies and I reinstall and then restore the most recent backup.

I can take a stab at splitting out the auto-restore functionality so the other pieces can be addressed separately.

**Comment by mleutenegger** [comment]
@silfreed That would be a great feature to have. Can you create a new PR with your changes once you are satisfied with the results?

**Comment by mleutenegger** [comment]
I am closing this PR due to inactivity.

**Pull request closed without merging**
